### ISSUE TITLE
CSS in Lgin Page 

### ISSUE THREAD

**Issue by franknh23** [franknh23/mineemoo#5]
https://mineemoo.nextmp.net/index.php/customer/account/login/

there is a ovlerlay of word in red can you fix this

**Comment by franknh23** [comment]
![4Capture](https://user-images.githubusercontent.com/24268648/92726290-a8f78500-f36d-11ea-9007-9de40c2b634f.JPG)

**Comment by ronakchauhan** [comment]
![137573595_126085449334431_4446111653950798684_n](https://user-images.githubusercontent.com/8565366/104127339-de36d280-5361-11eb-85c3-a9f177de9461.png)

fixed
